[f, revertClass] = tofloat(f);
PQ = paddedsize(size(f));
sig = 10;
Fp = fft2(f, PQ(1), PQ(2));
Hp = lpfilter('gaussian', PQ(1), PQ(2), 2*sig);
Gp = Hp.*Fp;
gp = ifft2(Gp);
gpc = gp(1:size(f, 1), 1:size(f, 2));
gpc = revertClass(gpc);
imshow(gp);
